package EZ::360::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'EZ::360::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:ez_360.db',
        user => '',
        password => '',
    }
);

=head1 NAME

EZ::360::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<EZ::360>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<EZ::360::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.26

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
